import os
from datetime import datetime, timezone

import psycopg
from dotenv import load_dotenv
from supabase import Client, create_client

load_dotenv()


# =============================================================================
# CLIENTS
# psycopg2 — direct PostgreSQL connection for CREATE TABLE (DDL statements).
# supabase-py — REST client for INSERT / UPDATE / SELECT (DML statements).
# Same pattern used in seed_db.py and db.py respectively.
# =============================================================================

_supabase_url = os.getenv("SUPABASE_URL")
_supabase_key = os.getenv("SUPABASE_KEY")
_db_url       = os.getenv("SUPABASE_DB_URL")

supabase: Client = create_client(_supabase_url, _supabase_key)


def _get_pg_connection():
    """Raw psycopg connection — only used for CREATE TABLE in create_tables()."""
    return psycopg.connect(_db_url, prepare_threshold=0)


# =============================================================================
# TABLE DEFINITIONS
# =============================================================================

_CREATE_SESSIONS_TABLE = """
CREATE TABLE IF NOT EXISTS sessions (
    session_id        TEXT PRIMARY KEY,
    customer_email    TEXT NOT NULL,
    started_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at          TIMESTAMPTZ,
    total_messages    INTEGER DEFAULT 0,
    agents_triggered  JSONB DEFAULT '[]',   -- e.g. ["faq", "chitchat"]
    escalated         BOOLEAN DEFAULT FALSE,
    escalation_reason TEXT,
    avg_confidence    NUMERIC(5, 4),        -- average confidence across all messages
    cache_hits        INTEGER DEFAULT 0,    -- how many responses were served from cache
    feedback_positive INTEGER DEFAULT 0,
    feedback_negative INTEGER DEFAULT 0
);
"""

_CREATE_MESSAGES_TABLE = """
CREATE TABLE IF NOT EXISTS messages (
    message_id           TEXT PRIMARY KEY,
    session_id           TEXT REFERENCES sessions(session_id),
    timestamp            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    user_message         TEXT NOT NULL,
    agent_response       TEXT NOT NULL,
    agent_type           TEXT,            -- chitchat / faq / order / returns / escalation
    intent               TEXT,            -- supervisor's route label (same as agent_type usually)
    confidence_score     NUMERIC(5, 4),  -- agent's self-reported confidence (null for chitchat)
    rag_best_score       NUMERIC(5, 4),  -- retriever's top CrossEncoder score (FAQ only)
    rag_chunks_retrieved INTEGER DEFAULT 0,
    cache_hit            BOOLEAN DEFAULT FALSE,
    response_time_ms     INTEGER,
    escalated            BOOLEAN DEFAULT FALSE,
    escalation_reason    TEXT,
    feedback             INTEGER DEFAULT 0  -- 1 = thumbs up, -1 = thumbs down, 0 = none
);
"""


# =============================================================================
# FUNCTION 1 — create_tables
# Run once at application startup. Safe to call every time — IF NOT EXISTS
# means it does nothing if the tables already exist.
# =============================================================================

_ALTER_MESSAGES_RETRY = """
ALTER TABLE messages
    ADD COLUMN IF NOT EXISTS retry_attempted  BOOLEAN DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS rewritten_query  TEXT,
    ADD COLUMN IF NOT EXISTS total_tokens     INTEGER DEFAULT 0,
    ADD COLUMN IF NOT EXISTS est_cost_usd     FLOAT   DEFAULT 0;
"""


def create_tables() -> None:
    """
    Create the sessions and messages tables in Supabase PostgreSQL if they
    don't exist yet. Called once when main.py starts up.
    Also adds retry columns if upgrading from an earlier version.
    """
    conn = _get_pg_connection()
    cursor = conn.cursor()
    cursor.execute(_CREATE_SESSIONS_TABLE)
    cursor.execute(_CREATE_MESSAGES_TABLE)
    cursor.execute(_ALTER_MESSAGES_RETRY)
    conn.commit()
    cursor.close()
    conn.close()
    print("[Tracker] Tables ready (sessions, messages).")


# =============================================================================
# FUNCTION 2 — log_session_start
# Called the moment a user sends their first message.
# Creates the session row with just the basics — everything else is updated
# progressively as messages come in, and again when the session ends.
# =============================================================================

def log_session_start(session_id: str, customer_email: str) -> None:
    """
    Insert a new row into the sessions table.

    Args:
        session_id:     UUID string — generated by main.py, also used as
                        LangGraph thread_id so we can correlate the two.
        customer_email: The email the user entered on the chat start screen.
    """
    supabase.table("sessions").insert({
        "session_id":     session_id,
        "customer_email": customer_email,
        "started_at":     datetime.now(timezone.utc).isoformat(),
    }).execute()


# =============================================================================
# FUNCTION 3 — log_message
# Called after every agent response.
# One call = one full exchange (user question + agent answer).
# =============================================================================

def log_message(
    message_id:           str,
    session_id:           str,
    user_message:         str,
    agent_response:       str,
    agent_type:           str,
    intent:               str,
    confidence_score:     float | None,
    rag_best_score:       float | None,
    rag_chunks_retrieved: int,
    cache_hit:            bool,
    response_time_ms:     int,
    escalated:            bool,
    escalation_reason:    str | None,
    retry_attempted:      bool = False,
    rewritten_query:      str | None = None,
    total_tokens:         int = 0,
    est_cost_usd:         float = 0.0,
) -> None:
    """
    Insert a new row into the messages table with full metadata for this exchange.
    """
    supabase.table("messages").insert({
        "message_id":           message_id,
        "session_id":           session_id,
        "timestamp":            datetime.now(timezone.utc).isoformat(),
        "user_message":         user_message,
        "agent_response":       agent_response,
        "agent_type":           agent_type,
        "intent":               intent,
        "confidence_score":     confidence_score,
        "rag_best_score":       rag_best_score,
        "rag_chunks_retrieved": rag_chunks_retrieved,
        "cache_hit":            cache_hit,
        "response_time_ms":     response_time_ms,
        "escalated":            escalated,
        "escalation_reason":    escalation_reason,
        "retry_attempted":      retry_attempted,
        "rewritten_query":      rewritten_query,
        "total_tokens":         total_tokens,
        "est_cost_usd":         est_cost_usd,
        "feedback":             0,
    }).execute()


# =============================================================================
# FUNCTION 4 — update_session_end
# Called when the session ends (user closes chat or browser tab disconnects).
# Fetches all messages for this session, computes aggregate stats, and writes
# the final summary back to the sessions row.
# =============================================================================

def update_session_end(session_id: str) -> None:
    """
    Compute aggregate stats from all messages in this session and write the
    final summary to the sessions table.

    Stats computed:
      - total_messages:    count of all messages
      - agents_triggered:  unique list of agent_type values used
      - escalated:         True if any message was escalated
      - escalation_reason: reason from the first escalated message
      - avg_confidence:    mean of all non-null confidence_score values
      - cache_hits:        count of messages where cache_hit = True
    """
    result = (
        supabase
        .table("messages")
        .select("agent_type, confidence_score, cache_hit, escalated, escalation_reason")
        .eq("session_id", session_id)
        .execute()
    )
    msgs = result.data or []

    if not msgs:
        # Session ended with no messages (user opened chat and closed immediately)
        supabase.table("sessions").update({
            "ended_at":       datetime.now(timezone.utc).isoformat(),
            "total_messages": 0,
        }).eq("session_id", session_id).execute()
        return

    # Unique agent types used in this session (order preserved via dict trick)
    agents_seen = list(dict.fromkeys(m["agent_type"] for m in msgs if m.get("agent_type")))

    # Average confidence — only messages where the agent reported a score
    confidence_values = [
        m["confidence_score"] for m in msgs if m.get("confidence_score") is not None
    ]
    avg_confidence = (
        round(sum(confidence_values) / len(confidence_values), 4)
        if confidence_values else None
    )

    # Escalation — True if any message triggered escalation
    escalated_msgs = [m for m in msgs if m.get("escalated")]
    escalated        = len(escalated_msgs) > 0
    escalation_reason = escalated_msgs[0]["escalation_reason"] if escalated_msgs else None

    cache_hits = sum(1 for m in msgs if m.get("cache_hit"))

    supabase.table("sessions").update({
        "ended_at":         datetime.now(timezone.utc).isoformat(),
        "total_messages":   len(msgs),
        "agents_triggered": agents_seen,
        "escalated":        escalated,
        "escalation_reason": escalation_reason,
        "avg_confidence":   avg_confidence,
        "cache_hits":       cache_hits,
    }).eq("session_id", session_id).execute()


# =============================================================================
# FUNCTION 5 — update_feedback
# Called when the user clicks thumbs up or thumbs down on a message bubble.
# Updates the feedback field on the specific message, then increments the
# matching counter on the parent session row.
# =============================================================================

def update_feedback(message_id: str, feedback: int) -> None:
    """
    Record a user's thumbs up (1) or thumbs down (-1) on a specific message.

    Also updates feedback_positive / feedback_negative counters on the
    session row so the analytics dashboard can show a feedback summary
    without querying all messages.

    Args:
        message_id: The message to update.
        feedback:   1 = thumbs up, -1 = thumbs down.
    """
    # Step 1 — update the message row
    supabase.table("messages").update({
        "feedback": feedback,
    }).eq("message_id", message_id).execute()

    # Step 2 — find which session this message belongs to
    result = (
        supabase
        .table("messages")
        .select("session_id")
        .eq("message_id", message_id)
        .execute()
    )
    if not result.data:
        return

    session_id = result.data[0]["session_id"]

    # Step 3 — increment the right counter on the session row.
    # We fetch current counts first, then increment in Python.
    # (Supabase REST API doesn't support atomic increment directly.)
    session_result = (
        supabase
        .table("sessions")
        .select("feedback_positive, feedback_negative")
        .eq("session_id", session_id)
        .execute()
    )
    if not session_result.data:
        return

    session = session_result.data[0]

    if feedback == 1:
        supabase.table("sessions").update({
            "feedback_positive": session["feedback_positive"] + 1,
        }).eq("session_id", session_id).execute()
    elif feedback == -1:
        supabase.table("sessions").update({
            "feedback_negative": session["feedback_negative"] + 1,
        }).eq("session_id", session_id).execute()


# =============================================================================
# FUNCTION 6 — get_live_metrics
# Called by GET /metrics/live every 5 seconds.
# Returns lightweight stats for the real-time panel in the chat UI.
# =============================================================================

def get_live_metrics() -> dict:
    """
    Return live metrics for the frontend's Live Metrics Panel.
    Shows all-time stats so the panel is never empty on low-usage days.
    Active sessions = sessions with no ended_at (still open right now).
    """
    sessions_result = (
        supabase
        .table("sessions")
        .select("session_id, ended_at, escalated, avg_confidence, cache_hits, total_messages, agents_triggered")
        .execute()
    )
    sessions = sessions_result.data or []

    messages_result = (
        supabase
        .table("messages")
        .select("intent, confidence_score, cache_hit, response_time_ms, feedback, escalated, retry_attempted")
        .execute()
    )
    msgs = messages_result.data or []

    total_sessions = len(sessions)
    active_sessions = sum(1 for s in sessions if s.get("ended_at") is None)
    total_messages  = len(msgs)
    escalation_count = sum(1 for s in sessions if s.get("escalated"))

    # Average confidence across all messages with a score
    conf_values = [m["confidence_score"] for m in msgs if m.get("confidence_score") is not None]
    avg_confidence = round(sum(conf_values) / len(conf_values), 4) if conf_values else 0.0

    # Cache hit rate
    cache_hits = sum(1 for m in msgs if m.get("cache_hit"))
    cache_hit_rate = round(cache_hits / total_messages, 4) if total_messages else 0.0

    # Escalation rate — calculated from messages not sessions,
    # because sessions.escalated is only set when session ends
    escalated_msgs  = sum(1 for m in msgs if m.get("escalated"))
    escalation_rate = round(escalated_msgs / total_messages, 4) if total_messages else 0.0

    # Average response time
    rt_values = [m["response_time_ms"] for m in msgs if m.get("response_time_ms") is not None]
    avg_response_time_ms = round(sum(rt_values) / len(rt_values)) if rt_values else 0

    # Intent breakdown — count messages per intent type
    intent_counts: dict[str, int] = {}
    for m in msgs:
        intent = m.get("intent") or "unknown"
        intent_counts[intent] = intent_counts.get(intent, 0) + 1

    # Feedback summary
    feedback_positive = sum(1 for m in msgs if m.get("feedback") == 1)
    feedback_negative = sum(1 for m in msgs if m.get("feedback") == -1)

    retry_count = sum(1 for m in msgs if m.get("retry_attempted"))
    retry_rate  = round(retry_count / total_messages, 4) if total_messages else 0.0

    return {
        "total_sessions":       total_sessions,
        "total_messages":       total_messages,
        "active_sessions":      active_sessions,
        "avg_confidence":       avg_confidence,
        "cache_hit_rate":       cache_hit_rate,
        "escalation_rate":      escalation_rate,
        "avg_response_time_ms": avg_response_time_ms,
        "retry_rate":           retry_rate,
        "intent_breakdown":     intent_counts,
        "feedback_positive":    feedback_positive,
        "feedback_negative":    feedback_negative,
    }
